version: "3"

services:
  strapi:
    build: .
    container_name: strapiexample
    restart: unless-stopped
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "3003:3003"
    depends_on:
      - mongoDB

  mongoDB:
    image: mongo
    container_name: mongoDB
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: adri
        MONGO_INITDB_ROOT_PASSWORD: adri123
        MONGO_INITDB_DATABASE: blog-backend
    networks:
      - strapi-app-network
    volumes:
      - .\DockerData\mongoDb\data:/data/db
    ports:
      - "27017:27017"
networks:
  strapi-app-network:
    driver: bridge
volumes:
  strapidata: